### ISSUE TITLE
external_dependencies.bzl not containing avr_toolchain

### ISSUE THREAD

**Issue by nico358** [es-ude/EmbeddedSystemsBuildScripts#14]
The documentation contains an error on https://embeddedsystemsbuildscripts.readthedocs.io/en/latest/AvrToolchain.html#instantiate-the-avrtoolchain-repository. The dash in 'strip-prefix' needs to be an underscore.

When applying the corrected example in my project I'm getting the following error: 
ERROR: /mnt/c/Users/current_sensing/WORKSPACE:19:1: file '@EmbeddedSystemsBuildScripts//:external_dependencies.bzl' does not contain symbol 'avr_toolchain'

The file external_dependencies.bzl contains indeed no such symbol, what can I do to run the BuildScripts properly?

**Comment by glencoe** [comment]
Hi,
thanks for pointing that error out. Actually you found a second error... the line in the readme should say
```
load(@EmbeddedSystemsBuildScripts//AvrToolchain:avr.bzl", "avr_toolchain")
```

**Comment by glencoe** [comment]
Both errors are corrected in the latest commit
