### ISSUE TITLE
Raise meaningful error when compiler is not found

### ISSUE THREAD

**Issue by glencoe** [es-ude/EmbeddedSystemsBuildScripts#18]
Currently when the compiler is not found the paths for the tools are just set to "none".
Raise a proper error instead that aborts the repository creation and tells the user what
tools are missing.

**Comment by boehnsins** [comment]
A basic check, and an error message in case the compiler is not found is included in 8d94fbe.

**Comment by boehnsins** [comment]
Merged in 5914e59c60c065c4d46f5b33c42c30b7455debe1.
