### ISSUE TITLE
How to disable the  "gnu99" feature

### ISSUE THREAD

**Issue by glencoe** [es-ude/EmbeddedSystemsBuildScripts#25]
You can disable a feature in this case "gnu99" by using

https://docs.bazel.build/versions/master/command-line-reference.html#flag--features

However we should document how that feature is called and that we enable it by default.

_Originally posted by @glencoe in https://github.com/es-ude/EmbeddedSystemsBuildScripts/pull/24#issuecomment-621072793_

**Comment by boehnsins** [comment]
documentation was added in 04150c8b6e620616296cfd4bdd52429cd7d81ab8 and 19cc4ea4ec79191f36f29fa2beb121a46aad7c14.
