### ISSUE TITLE
Follow naming conventions for targets created via macros

### ISSUE THREAD

**Issue by glencoe** [es-ude/EmbeddedSystemsBuildScripts#29]
The currently created name for the upload scripts is _(originaltargetname)Upload.
The conventions stated at https://docs.bazel.build/versions/master/skylark/macros.html#conventions
recommends originaltargetname_upload instead.

**Comment by boehnsins** [comment]
Changes were added in commit 8885326d68835df79ec49abe838769ec2b1c2f50 and can be merged via pull request #28
