### ISSUE TITLE
platform target ElasticNode_v4_monitor has no programmer

### ISSUE THREAD

**Issue by DerDavidos** [es-ude/EmbeddedSystemsBuildScripts#39]
Probably only " "@AvrToolchain//platforms/programmer:stk500", " needs to be added in Toolchains/Avr/platforms/BUILD.tpl to ElasticNode_v4_monitor and ElasticNode_v3_monitor to add the programmer.

**Comment by pixelboehm** [comment]
The monitor board has a `atmega32u4` mcu, which can be flashed with the dfu programmer.
For that just use the following parameter in the target binary for the monitor target: `upload_script = "@AvrToolchain//:dfu_upload_script"`

**Comment by DerDavidos** [comment]
For now we will still use the avrdude_upload_script. So the programmer is added.
